int controller_Lenzuen_loadFromText(LinkedList* pArrayListEmployee,LinkedList* pArrayListPilotos);
int controller_Lenzuen_relacionarId(LinkedList* listaPilotos,int id);
int controller_Lenzuen_ListaVuelos(LinkedList* pArrayListaVuelos,LinkedList* pArrayListaPilotos);
int controller_Lenzuen_ListaPilotos(LinkedList* pArrayListaPilotos);
int controller_Lenzuen_ListaCantidadPasajeros(LinkedList* pArrayListaVuelos);
int controller_Lenzuen_ListaCantidadPasajerosIrlanda(LinkedList* pArrayListaVuelos);
int controller_Lenzuen_saveAsText(char* path , LinkedList* pArrayListaVuelo);
int controller_Lenzuen_FiltrarVuelosCortos(LinkedList* pArrayListaVuelos);
int controller_Lenzuen_FiltrarVuelosPortugal(LinkedList* pArrayListaVuelos);
int controller_Lenzuen_FiltrarVuelosPiloto(LinkedList* pArrayListaVuelos);
int controller_Lenzuen_FiltrarPilotoPorNombre(LinkedList* pArrayListaPilotos);
